# Generated by Django 4.0.3 on 2022-03-25 07:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('middleware', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='imdb',
            name='directors',
            field=models.CharField(default=1, max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='imdb',
            name='imdb_rating',
            field=models.CharField(default=1, max_length=4),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='imdb',
            name='plot',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
    ]
