# Generated by Django 4.0.3 on 2022-03-25 07:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('middleware', '0002_imdb_directors_imdb_imdb_rating_imdb_plot'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imdb',
            name='release_date',
            field=models.DateField(null=True),
        ),
    ]
