# Generated by Django 4.0.3 on 2022-03-25 07:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('middleware', '0003_alter_imdb_release_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imdb',
            name='directors',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='imdb',
            name='plot',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='imdb',
            name='trailer',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
